# For importing data from the legacy database
legacy_db:
  host: localhost
  database: icu_db_copy
  username: username
  password: password
  encoding: latin1

# For importing data from the ratings database
legacy_db:
  host: localhost
  database: ratings_development
  username: username
  password: password
  encoding: utf8

# Set this to just "pasword" if you want to store unencrypted passwords
password_encryptor: 'Digest::MD5.hexdigest("#{password}#{salt}")'

# Valid characters in a season ticket and how to reorder them
season_ticket:
  base: HAgDXP7BcK3fmzh2CaMEdZxyrTWL9tknNe84G6bRwpYF
  shuffle: str.reverse

secret_key_base: 4fbd352d214c2118a7fd152173de8dd358dcd07289a8eb751e332e279848a905fd1228b5e51e4ec60c14b41d69c93eetea7a35bb8854d99356a0f13091bd08b7

session_key: www_session

# Stripe
stripe:
  production:
    public: "pk_live_aYo71Qp4R1XBgsQ1ObaE8CpM"
    secret: "sk_live_5ay80yu1hJb45gV9ul6fb2zt"
  development:
    public: "pk_test_aYo71Qp4R1XBgsQ1ObaE8CpM"
    secret: "sk_test_5ay80yu1hJb45gV9ul6fb2zt"
  test:
    public: "pk_test_aYo71Qp4R1XBgsQ1ObaE8CpM"
    secret: "sk_test_5ay80yu1hJb45gV9ul6fb2zt"

# Mailgun
mailgun:
  password: "32pw166im7f9"
  secret: "key-1uyak4ijwrw1v1xcu1ggdo3eq954mi21"
  public: "pubkey-1oo8fl2--5ghabi12k32boslf3-576x3"
