development:
  adapter: mysql2
  encoding: utf8
  database: www_development
  pool: 5
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock
  strict: false

test:
  adapter: mysql2
  encoding: utf8
  database: www_test
  pool: 5
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock
  strict: false

production:
  adapter: mysql2
  encoding: utf8
  database: www_production
  pool: 5
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock
  strict: false
